baseURL: "https://blusewill.ml"
title: blusewill's Official Website
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Single Donation
                  url: https://streamelements.com/blusewill/tip
                  weight: 10
                - name: Store
                  url: https://blusewill.gumroad.com
                - name: Website Source Code
                  url: https://github.com/blusewill/website

    zh-tw:
        languageName: "Chinese Traditional"
        languageAltTitle: Chinese Traditional
        weight: 2
        title: 小品大大
        profileMode:
            enabled: true
            title: 小品大大
            imageUrl: "img/pfp.png"
            imageWidth: 128
            imageHeight: 128
            imageTitle: ProfileMode image
            subtitle: "不會3D建模的3D建模師 | Linux 使用者 | 直播主 | 旋風忍者配樂剪輯員 | YouTuber "
            buttons:
                - name: Youtube
                  url: https://youtube.com/小品大大blusewill
                - name: 圖奇 (Twitch)
                  url: https://twitch.tv/blusewill
        menu:
            main:
                - name: 貼文
                  url: posts
                  weight: 5
                - name: 搜尋
                  url: searchtw
                  weight: 10
                - name: 斗內
                  url: https://streamelements.com/blusewill/tip
                  weight: 10
                - name: 商店
                  url: https://blusewill.gumroad.com
                  weight: 10
                - name: 網站原始碼
                  url: "https://github.com/blusewill/website"


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: blusewill's Website
  description: "Just blusewill's Offical Website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: [img/pfp.png]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  

  assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: "favicon.ico"
  favicon16x16: "favicon16.png"
  favicon32x32: "favicon32.png"


  label:
    text: "blusewill"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "blusewill"
    subtitle: "Bad 3D Modeler | Linux User | Streamer | Ninjago Soundtrack Editor | YouTuber "
    imageUrl: "img/pfp.png"
    imageWidth: 128
    imageHeight: 128
    imageTitle: Profile Picture
    buttons:
      - name: Youtube
        url: https://youtube.com/c/小品大大blusewill
      - name: Twitch
        url: https://twitch.tv/blusewill

  # home-info mode
  homeInfoParams:
    Title: "Welcome"
    Content: To blusewill's Offical Website (Blog)

  socialIcons:
    - name: twitter
      url: "https://twitter.com/bluesewill"
    - name: github
      url: "https://github.com/blusewill"

 
  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
menu:
  main:
    - identifier: Posts
      name: Posts
      url: posts
      weight: 10
    - identifier: tags
      name: Single Donation
      url: https://streamelements.com/blusewill/tip
      weight: 20
      weight: 30
    - identifier: Gumroad
      name: Store
      url: https://blusewill.gumroad.com/
    - identifier: Source
      name: Website Source Code
      url: https://github.com/blusewill/website

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
